### ISSUE TITLE
Slack notification does not fire if I chose "Notify author" via Slack only

### ISSUE THREAD

**Issue by vqmarkman** [sundeck-io/OpsCenter#141] opened 2023-08-08 19:58 UTC
1. Logged in to Snowflake, started the app (1.5 official installation from the market place) and created Sundeck account via SSO
   (https://app.sundeck.io/us-west-2/iopkxr81/account-settings)
   
2. Went to "Account Settings", chose "Add to Slack" and went through the whole process successfully.

3. Created probe, see below:

<img width="820" alt="Screenshot 2023-08-08 at 12 53 55 PM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/5d47477f-bfa9-42d2-8cb1-2b23f4fac756">

4. Ran query: `select /* vicky - notify via slack (account with SSO integration) */ system$wait(120);`

Query execution was cancelled successfully, but I did not get Slack notification.

5. Results of `select * from reporting.probe_actions;` are below:

<img width="1640" alt="Screenshot 2023-08-08 at 12 56 17 PM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/a780f4ba-1590-4c60-b196-a241c80261db">

6. My Slack email is vicky@sundeck.io, so is my email for user vicky in Snowflake account.

<img width="968" alt="Screenshot 2023-08-08 at 12 59 13 PM" src="https://github.com/sundeck-io/OpsCenter/assets/104043363/ae4cf238-2669-43ac-87d7-58f9214f433b">

**Comment by joshelser** [comment] 2023-08-08 20:07
Curious that your `PROBE_ACTIONS` view doesn't have a `SLACK` attribute in the `ACTIONS_TAKEN` object. That seems to be the problem.

**Comment by joshelser** [comment] 2023-08-08 20:15
Can you please verify the output of this query in your Snowflake account?

```
select name, email from snowflake.account_usage.users where name = 'vicky';
```

We would be missing the `SLACK` element in `PROBE_ACTIONS` if the join against `internal.sfusers` (which is a view on snowflake.account_usage.users) doesn't have a value for the `email` column.

**Comment by joshelser** [comment] 2023-08-08 20:28
Chatting with Vicky directly:

* The `snowflake.account_usage.users` view had the expected username and email.
* We found that the `internal.sfusers` table was empty.
* The task is allegedly set to run.

That's the cause. Need to figure out why the task is not running as expected.

**Comment by joshelser** [comment] 2023-08-08 20:46
For whatever reason, `call admin.run_as_app('select * from internal.sfusers');` showed no rows and the `TASKS.SFUSER_MAINTENANCE` did not appear in task history (even after `execute task TASKS.SFUSER_MAINTENANCE`).

By running `call admin.run_as_app('insert into internal.sfusers select name, email from snowflake.account_usage.users');`, this filled out the `internal.sfuser` table, and then Slack "notify author" notification worked as expected.

We don't know why the task history appeared incomplete or was not successfully running. However, getting to work on #57 will be the right way to get this info out of the app. I think we should close this issue and refer to these steps as good debugging for the future.

WDYT, @vqmarkman ? Did I miss anything?

**Comment by vqmarkman** [comment] 2023-08-08 20:50
@joshelser , you did not miss anything. I agree that we should implement #57 , then debugging will be much easier. Nothing can be done at the moment regarding this problem. We should close it for now imo.

**Closed** 2023-08-08 21:29 UTC
